<div class ="container">
<h2>National Parks List</h2>
<hr>
	<div class="col col-md-10 col-md-offset-1 col-centered">
		<div class="row center-block">
			<table class="table table-striped table-hover table-bordered">
				<th>
					<td><strong>Park Name</strong></td>
					<td><strong>Location</strong></td>
					<td><strong>Date Established</strong></td>
					<td><strong>Area (in acres)</strong></td>
				</th>
				<?php foreach($pagedParks as $park) : ?>
					<tr>
						<td><?= $park['id'] ?></td>
						<td><?= $park['name'] ?></td>
						<td><?= $park['location'] ?></td>
						<td><?= $park['date_established'] ?></td>
						<td><?= $park['area_in_acres'] ?></td>
					</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	<div class="col col-md-10 col-md-offset-2 col-centered">
		<div class="row">
			<nav>
				<ul class="pagination">
					<li>
						<a href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
					<?php foreach($pageNumbers as $pageNumber) : ?>
						<li><a href="?page=<?= $pageNumber ?>"><?= $pageNumber + 1?></a></li>
					<?php endforeach; ?>
					<li>
						<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</div>