<style>
.error {
	color: #A94442;
}
</style>
<div class="col col-md-4">
	<form method="POST">
		<div class="form-group <?= (isset($errors['name'])) ? 'has-error' : '' ?>" >
			<label for="name">Park Name</label>
			<input type="text" class="form-control" id="name" placeholder="Name" name="name">
			<small class="error"><?= (isset($errors['name'])) ? $errors['name'] : '' ?></small>
		</div>
		<div class="form-group <?= (isset($errors['location'])) ? 'has-error' : '' ?>">
			<label for="location">Location</label>
			<input type="text" class="form-control" id="location" placeholder="Location" name="location">
			<small class="error"><?= (isset($errors['location'])) ? $errors['location'] : '' ?></small>
		</div>
		<div class="form-group <?= (isset($errors['date_established'])) ? 'has-error' : '' ?>">
			<label for="date_established">Date Established</label>
			<input type="text" class="form-control" id="date_established" placeholder="Date Est." name="date_established">
			<small class="error"><?= (isset($errors['date_established'])) ? $errors['date_established'] : '' ?></small>
		</div>
		<div class="form-group <?= (isset($errors['area_in_acres'])) ? 'has-error' : '' ?>">
			<label for="area_in_acres">Area (in acres)</label>
			<input type="text" class="form-control" id="area_in_acres" placeholder="Area" name="area_in_acres">
			<small class="error"><?= (isset($errors['area_in_acres'])) ? $errors['area_in_acres'] : '' ?></small>
		</div>
		<div class="form-group <?= (isset($errors['description'])) ? 'has-error' : '' ?>">
			<label for="description">Description</label>
			<textarea type="text" class="form-control" rows="3" id="description" placeholder="Description" name="description"></textarea>
			<small class="error"><?= (isset($errors['description'])) ? $errors['description'] : '' ?></small>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>